import Head from 'next/head'

import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Content from '../sections/Content'
import { useSession } from '@supabase/auth-helpers-react'
import Signin from '../components/SignIn'

export default function Home() {
  const session = useSession()

  if (!session) {
    return (
      <div className='height relative overflow-hidden w-full h-[100vh] sm:h-[100vh] flex justify-center items-center'>
        <Signin />
      </div>
    )
  }

  const content = () => {
    if (!session) {
      return <Signin />
    }
  }
  return (
    <div className=''>
      <Head>
        <title>BabyNamer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/baby-face-icon.png' />
      </Head>
      <div className='height relative overflow-hidden'>
        <Navbar />
        {/* {content()} */}
        <Content />
        <Footer />
      </div>
    </div>
  )
}
